### ISSUE TITLE
記号が含まれるパスワードでサインアップできない

### ISSUE THREAD

**Issue by tama9o** [KouSei089/Mikke#365]
サインアップさせていただこうと思って画面から入力したところ、記号が含まれるパスワードで登録できません。
メッセージは以下なので、記号も使用可能な認識でいます。

```
 パスワードは8文字以上にしてください。英数字の両方を含む必要があります 
```

以下の正規表現が間違っているのではないかと。

https://github.com/KouSei089/Mikke/blob/4cbc7e9fc31da9b8972c22002446d97ca75a9762/app/models/user.rb#L4

```
noname@www:~$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
noname@www:~$ irb
irb(main):001:0> VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,}+\z/i.freeze
=> /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,}+\z/i
irb(main):002:0> VALID_PASSWORD_REGEX.match('hogefuga')
=> nil
irb(main):003:0> VALID_PASSWORD_REGEX.match('hogefug1')
=> #<MatchData "hogefug1">
irb(main):004:0> VALID_PASSWORD_REGEX.match('hogefug@')
=> nil
irb(main):005:0> VALID_PASSWORD_REGEX.match('hogefug1@')
=> nil
```

**Comment by KouSei089** [comment]
issueまで作っていただき、ご指摘ありがとうございます！！

`パスワードは8文字以上にしてください。英数字の両方を含む必要があります `
上記の文章で、"記号は使わない" と勝手に自己認識してしまってました。
自分の実装した場合だと `記号等は使用できません。` 等のメッセージを表示するか、記号も扱えるようにするべきでした。

指摘いただいたissueの修正に関しましたは、記号等の入力は必須ではないけど、記号も扱えるように正規表現を修正しようと思います。
またサービスへの登録、ありがとうございます！
